import React, { useEffect, useState } from "react";
import PageHeader from "../../layout/PageHeader";
import { useDispatch, useSelector } from "react-redux";
import {
  fetchTokenActivationHistory,
  generateUpgradeToken,
} from "../../redux/slices/registrationSlice";
import { formatDate } from "../../utils/dateFormatter";
import SmartTable from "../../components/SmartTable";
import Pagination from "../../components/Pagination";
import TokenTypeBadge from "../../partial/registration-request/TokenTypeBadge";
import { ArrowUpCircle } from "lucide-react";
import ModalAction from "../../components/ModalAction";
import { handleResponse } from "../../utils/helpers";
import PlanBadge from "../../partial/registration-request/PlanBadge";

const TokenActivationLogsPage = () => {
  const dispatch = useDispatch();

  const [currentPage, setCurrentPage] = useState(1);
  const [itemsPerPage, setItemsPerPage] = useState(10);

  const [upgradeState, setUpgradeState] = useState({
    open: false,
    row: null,
  });

  const {
    isFetchingTokenActivationHistory,
    tokenActivationHistory,
    isGeneratingUpgradeToken,
  } = useSelector((state) => state.registration);

  const { tokens, pagination } = tokenActivationHistory || {};

  const fetchTokes = () => {
    dispatch(
      fetchTokenActivationHistory({ page: currentPage, limit: itemsPerPage }),
    );
  };

  useEffect(() => {
    fetchTokes();
  }, [currentPage, itemsPerPage]);

  const columns = [
    {
      key: "restaurant",
      label: "Restaurant",
      sortable: true,
      render: (row) => (
        <div className="flex flex-col">
          <span className="font-semibold text-slate-800">
            {row.restaurant_name || "—"}
          </span>
          <span className="text-xs text-slate-500">
            {row.email || "No email"}
          </span>
        </div>
      ),
    },

    {
      key: "token_type",
      label: "Type",
      sortable: true,
      render: (row) => <TokenTypeBadge type={row.token_type} />,
    },

    {
      key: "plan",
      label: "Plan",
      sortable: true,
      render: (row) => <PlanBadge plan={row.plan_interest} />,
    },

    {
      key: "license",
      label: "License",
      sortable: false,
      render: (row) => (
        <div className="flex flex-col text-xs text-slate-600">
          <span className="font-mono break-all">{row.license_id}</span>

          {row.upgrade_from_license_id && (
            <span className="text-[10px] text-slate-400 mt-1">
              From: {row.upgrade_from_license_id}
            </span>
          )}
        </div>
      ),
    },

    {
      key: "generated_by",
      label: "Generated By",
      sortable: true,
      render: (row) => (
        <span className="text-sm text-slate-700">
          Admin #{row.generated_by_user_id}
        </span>
      ),
    },

    {
      key: "created_at",
      label: "Created On",
      sortable: true,
      render: (row) => (
        <span className="text-sm text-slate-600">
          {formatDate(row.created_at, "longTime")}
        </span>
      ),
    },
  ];

  const rowActions = [
    {
      label: "Upgrade Plan",
      icon: ArrowUpCircle,
      color: "blue",

      disabled: (row) =>
        !(
          row.token_type === "activation" &&
          row.plan === "free" &&
          row.license_id
        ),

      onClick: (row) => {
        setUpgradeState({
          open: true,
          row,
        });
      },
    },
  ];

  const handleUpgradeConfirm = async () => {
    const row = upgradeState.row;

    if (!row?.license_id) return;

    const values = {
      licenseId: row.license_id,
    };

    await handleResponse(dispatch(generateUpgradeToken(values)), () => {
      fetchTokes();
      setUpgradeState({ open: false, row: null });
    });
  };

  return (
    <>
      <div className="space-y-6">
        <PageHeader title={"Activation Logs"} showBackButton />

        <SmartTable
          title="Items"
          totalcount={pagination?.total}
          data={tokens}
          columns={columns}
          actions={rowActions}
          loading={isFetchingTokenActivationHistory}
        />

        <Pagination
          totalItems={pagination?.total}
          currentPage={currentPage}
          pageSize={itemsPerPage}
          totalPages={pagination?.pages}
          onPageChange={(page) => setCurrentPage(page)}
          maxPageNumbers={5}
          showPageSizeSelector={true}
          onPageSizeChange={(size) => {
            setCurrentPage(1);
            setItemsPerPage(size);
          }}
        />
      </div>

      <ModalAction
        id="upgrade-license-modal"
        isOpen={upgradeState.open}
        onClose={() => setUpgradeState({ open: false, row: null })}
        onConfirm={handleUpgradeConfirm}
        title="Upgrade to Pro Plan"
        description={`Are you sure you want to upgrade ${
          upgradeState.row?.restaurant_name || "this restaurant"
        } to Pro plan?`}
        theme="success"
        confirmText="Upgrade"
        cancelText="Cancel"
        loading={isGeneratingUpgradeToken}
      />
    </>
  );
};

export default TokenActivationLogsPage;
