export const ROUTE_PATHS = {
  // Dashboard & Core
  HOME: "/",
  OUTLET_DASHBOARD: "/outlet-dashboard",
  ORDER_DISPLAY: "/order-display",
  GUIDE: "/guide",
  MY_PROFILE: "/my-profile",

  // Reports
  ALL_REPORTS: "/reports",
  REPORTS_DAILY_SALES: "/reports/daily-sales",
  REPORTS_DAILY_SALES_DETAILS: "/reports/daily-sales/details",
  REPORTS_ITEM_SALES: "/reports/item-sales",
  REPORTS_CATEGORY_SALES: "/reports/category-sales",
  REPORTS_SECTION_SALES: "/reports/section-sales",
  REPORTS_STATION_SALES: "/reports/station-sales",
  REPORTS_STAFF_SALES: "/reports/staff-sales",
  REPORTS_PAYMENT_MODE: "/reports/payment-mode",
  REPORTS_TAX: "/reports/tax-report",
  REPORTS_TAX_DETAILS: "/reports/tax-report/details",
  REPORTS_SERVICE_TYPE_BREAKDOWN: "/reports/service-type-breakdown",
  REPORTS_OUTSIDE_COLLECTION: "/reports/outside-collections",
  REPORTS_SHIFT_HISTORY: "/shift-history",
  REPORTS_SHIFT_HISTORY_DETAILS: "/shift-history/details",
  REPORTS_DUE: "/reports/due-report",
  REPORTS_NC: "/reports/nc-report",
  REPORTS_CANCELLATION: "/reports/cancellation-report",
  REPORTS_DISCOUNT: "/reports/discount-report",
  REPORTS_ADJUSTMENT: "/reports/adjustment-report",
  REPORTS_RUNNING_ORDERS: "/running-orders",
  REPORTS_RUNNING_TABLES: "/running-tables",
  REPORTS_DAY_END_SUMMARY: "/day-end-summary",
  REPORTS_DAY_END_SUMMARY_DETAILS: "/day-end-summary/details",
  REPORTS_LIVE_ORDERS: "/live-orders",
  REPORTS_LIVE_OPERATIONS: "/live-operations",

  // NC Reasons
  ALL_NC_REASONS: "/nc-reasons",

  // Inventory
  INVENTORY_SUMMARY: "/inventory",
  ALL_INVENTORY_ITEMS: "/inventory-items",
  INVENTORY_ITEMS_ADD: "/inventory-items/add",
  INVENTORY_ITEMS_DETAILS: "/inventory-items/details",
  INVENTORY_ITEMS_BATCHES: "/inventory-items/batches",
  ALL_INVENTORY_CATEGORIES: "/inventory-categories",
  ALL_INVENTORY_UNITS: "/inventory/units",
  ALL_INVENTORY_MOVEMENTS: "/inventory-movements",
  ALL_INVENTORY_WASTAGE: "/inventory-wastage",
  ALL_INVENTORY_INGREDIENTS: "/ingredients",
  INVENTORY_INGREDIENTS_ADD: "/ingredients/add",

  // Vendors & Purchase Orders
  ALL_VENDORS: "/inventory-vendors",
  VENDORS_ADD: "/inventory-vendors/add",
  VENDORS_DETAILS: "/inventory-vendors/details",
  ALL_PURCHASE_ORDERS: "/purchase-orders",
  PURCHASE_ORDERS_ADD: "/purchase-orders/add",
  PURCHASE_ORDERS_DETAILS: "/purchase-orders/details",

  // Recipes
  ALL_RECIPES: "/recipes",
  RECIPES_ADD: "/recipes/add",
  RECIPES_DETAILS: "/recipes/details",
  ALL_PREP_RECIPES: "/prep-recipes",
  PREP_RECIPES_ADD: "/prep-recipes/add",
  PREP_RECIPES_DETAILS: "/prep-recipes/details",

  // Menu Management
  ALL_MENU_CATEGORIES: "/categories",
  ALL_MENU_ITEMS: "/items",
  MENU_ITEMS_DETAILS: "/items/details",
  MENU_ITEMS_ADD: "/items/add",
  MENU_ITEMS_BULK_ADD: "/items/bulk-add",
  MENU_ITEMS_BULK_ADD_SUMMARY: "/items/bulk-add/summary",
  MENU_MEDIA: "/menu-media",
  MENU_MEDIA_QR_CODES: "/menu-media/qr-codes",
  ALL_ADDONS_GROUPS: "/addons",
  ALL_ADDONS_ITEMS: "/addons/item",
  ALL_TAX_TYPES: "/tax-types",
  ALL_TAX_COMPONENTS: "/tax-components",
  ALL_TAX_GROUPS: "/tax-groups",
  TAX_GROUPS_DETAILS: "/tax-groups/details",

  // Operations
  ALL_ORDERS: "/orders",
  ORDER_DETAILS: "/orders/details",
  ALL_CUSTOMERS: "/customers",
  CUSTOMER_DETAILS: "/customers/details",
  ALL_STATIONS: "/stations",
  ALL_PRINTERS: "/printers",
  ALL_TABLE_QR: "/tables-qr",
  ALL_FLOORS: "/floors",
  FLOORS_TABLES: "/floors/tables",
  FLOORS_SECTIONS_TABLES: "/floors/sections/tables",
  TABLE_HISTORY: "/floors/sections/tables/history",
  TABLE_REPORT: "/floors/sections/tables/report",
  TABLE_KOT: "/floors/sections/tables/kot",

  // Organization
  ALL_OUTLETS: "/outlets",
  OUTLET_DETAILS: "/outlets/details",
  OUTLET_ADD: "/outlets/add",
  OUTLET_DELETE: "/outlets/delete",
  OUTLET_LOGO: "/outlet-logo",
  ALL_USERS: "/users",
  USER_DETAILS: "/users/details",
  USER_ADD: "/users/add",
  ALL_SUPER_ADMINS: "/super-admins",
  SUPER_ADMIN_ADD: "/super-admins/add",
  REGISTRATION_REQUESTS: "/registration-requests",
  REGISTRATION_REQUESTS_ADD: "/registration-requests/add",
  TOKEN_GENERATION_LOGS: "/token-generation-logs",

  // SUBSCRIPTIONS
  SUBSCRIPTION_DASHBOARD: "/subscriptions",
  MY_SUBSCRIPTION: "/my-subscription",
  SUBSCRIPTION_GLOBAL_PRICING: "/global-pricing",
  SUPER_ADMIN_SUBSCRIPTION_PRICING: "/super-admin-pricing",
  SUPER_ADMIN_OUTLET_SUBSCRIPTION: "/super-admin-pricing/outlets",
  OUTLET_PRICING: "/outlet-pricing",
  SUBSCRIPTION_LIST: "/subscriptions-list",

  // System
  ALL_SETTINGS: "/settings",
  SETTING_DETAILS: "/settings/categories",
  SUPPORT_CHAT: "/support",
  ALL_VERSIONS: "/versions",
  VERSION_ADD: "/versions/add",
  VERSION_DETAILS: "/versions/details",
};
